name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_rust_macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: |
          cd rust
          cargo build --release
    - name: Run tests
      run: |
          cd rust
          cargo test

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shs-macos
        path: ./rust/target/release/shs

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    #   with:
    #       tag_name: ${{ github.ref }}
    #       release_name: Release ${{ github.ref }}
    #       draft: false
    #       prerelease: false

    # - name: Create ZIP
    #   run: |
    #     cd rust/target/release
    #     zip shs-macos.zip shs
      
    # - name: Upload Release Asset
    #   id: upload_release_asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    #   with:
    #       upload_url: ${{ steps.create_release.outputs.upload_url }}
    #       asset_path: ./rust/target/release/shs-macos.zip
    #       asset_name: shs-macos.zip
    #       asset_content_type: application/zip

  build_rust_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: |
        cd rust
        cargo build --release
    - name: Run tests
      run: |
        cd rust
        cargo test
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shs-linux
        path: ./rust/target/release/shs

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    #   with:
    #       tag_name: ${{ github.ref }}
    #       release_name: Release ${{ github.ref }}
    #       draft: false
    #       prerelease: false

    # - name: Create ZIP
    #   run: |
    #     cd rust/target/release
    #     zip shs-linux.zip shs
      
    # - name: Upload Release Asset
    #   id: upload_release_asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    #   with:
    #       upload_url: ${{ steps.create_release.outputs.upload_url }}
    #       asset_path: ./rust/target/release/shs-linux.zip
    #       asset_name: shs-linux.zip
    #       asset_content_type: application/zip

  build_rust_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: |
        cd rust
        cargo build --release
    - name: Run tests
      run: |
        cd rust
        cargo test
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shs-windows
        path: ./rust/target/release/shs.exe

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.MY_PAT }} 
    #   with:
    #       tag_name: ${{ github.ref }}
    #       release_name: Release ${{ github.ref }}
    #       draft: false
    #       prerelease: false

    # - name: Create ZIP
    #   run: |
    #     cd rust/target/release
    #     zip shs-win.zip shs
      
    # - name: Upload Release Asset
    #   id: upload_release_asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    #   with:
    #       upload_url: ${{ steps.create_release.outputs.upload_url }}
    #       asset_path: ./rust/target/release/shs-win.zip
    #       asset_name: shs-win.zip
    #       asset_content_type: application/zip